name: Web deployment trigger
on:
  push:
    branches:
      - master
    tags:
      - v*
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Determine environment
        id: env
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "target=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "target=staging" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "target=production" >> $GITHUB_OUTPUT
          else
            echo "target=none" >> $GITHUB_OUTPUT
          fi
      
      - name: Trigger deployment workflow
        if: steps.env.outputs.target != 'none'
        uses: osu-tournament-rating/otr-web/.github/workflows/deploy.yml@master
        with:
          target: ${{ steps.env.outputs.target }}